name: travel_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  smooth_page_indicator: ^1.1.0
  flutter_bloc: ^8.1.5
  google_fonts: ^6.2.1
  gap: ^3.0.1
  awesome_extensions: ^2.0.14
  flutter_svg: ^2.0.10+1
  google_maps_flutter: ^2.6.1
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  flag: ^7.0.0
  shared_preferences: ^2.2.3
  supabase_flutter: ^2.5.2
  formz: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  assets:
    - assets/images/
    - assets/vector/SVG/
    - assets/vector/
    - assets/vector/linear/
    - assets/vector/essential/
    - assets/vector/money/
    - assets/vector/notifications/
    - assets/vector/type_characters/

  uses-material-design: true
flutter_intl:
  enabled: true
