name: travel_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  smooth_page_indicator: ^1.1.0
  flutter_bloc: ^8.1.5
  google_fonts: ^6.2.1
  gap: ^3.0.1
  awesome_extensions: ^2.0.14
  flutter_svg: ^2.0.10+1
  google_maps_flutter: ^2.6.1
  intl: any
  flutter_localizations:
    sdk: flutter
  flag: ^7.0.0
  shared_preferences: ^2.2.3
  supabase_flutter: ^2.5.2
  formz: ^0.7.0
  dartz: ^0.10.1
  skeletonizer: ^1.1.2+1
  cached_network_image: ^3.3.1
  geobase: ^1.1.0
  photo_view: ^0.15.0
#  fluster: ^1.2.0
#  google_maps_cluster_manager: ^3.1.0
#  flutter_map: ^6.1.0
  google_maps_cluster_manager_2: ^3.1.0
  url_launcher: ^6.2.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dev: ^1.0.0
  rate_in_stars: ^0.0.3
  flutter_rating_stars: ^1.1.0
  rxdart: ^0.27.7
  translator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^3.0.0

flutter:

  assets:
    - assets/images/
    - assets/vector/SVG/
    - assets/vector/
    - assets/vector/linear/
    - assets/vector/essential/
    - assets/vector/money/
    - assets/vector/notifications/
    - assets/vector/type_characters/

  uses-material-design: true
flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/Screenshot_2024-05-16_161419-removebg-preview.png"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21